#!/bin/sh
if [[ $# != 1 ]] ; then
    >&2 echo "Укажите ровно один аргумент соответствующий количеству тестов, которые будете вводить!"
    exit 1
fi
make clean
make readingassistant
tests=$(ls -1 | grep tests-) 
for i in $(seq 1 $1); do
   echo "Введите $i тест:"
   ./readingassistant >$tests/$i.dat 
   echo "Введите ответ на $i тест:"
   ./readingassistant >$tests/$i.ans
done
