#!/bin/sh
if [[ $# == 3 ]]; then
    mkdir tests-$1-$2
    cd tests-$1-$2
    eval touch {1..${3}}.dat {1..${3}}.ans
else
    >&2 echo "Должно быть 3 аргумента(номер контеста, номер задачи и количество тестов)"
    >&2 echo "Например: \"createtests sm2 3 10\"."
    exit 1
fi

